version: "3.8"

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  # Node.js application service
  app:
    build: .
    container_name: nodejs-app
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://root:example@mongodb:27017/myapidb?authSource=admin
      PORT: 5000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodb

volumes:
  mongo_data:
